<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\Timezone;

class CreateTimezonesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('timezones', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->string('country_code');
            $table->string('country_name');
            $table->string('time_zone');
            $table->string('gmt_offset');
            $table->timestamps();
        });

        
Timezone::create([ "country_code" => "AF", "country_name" => "Afghanistan", "time_zone" => "Asia/Kabul","gmt_offset" => "UTC +04:30" ]);
Timezone::create([ "country_code" => "AL", "country_name" => "Albania", "time_zone" => "Europe/Tirane","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "DZ", "country_name" => "Algeria", "time_zone" => "Africa/Algiers","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "AS", "country_name" => "American Samoa", "time_zone" => "Pacific/Pago_Pago","gmt_offset" => "UTC -11:00" ]);
Timezone::create([ "country_code" => "AD", "country_name" => "Andorra", "time_zone" => "Europe/Andorra","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "AO", "country_name" => "Angola", "time_zone" => "Africa/Luanda","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "AI", "country_name" => "Anguilla", "time_zone" => "America/Anguilla","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/Casey","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/Davis","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/DumontDUrville","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/Mawson","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/McMurdo","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/Palmer","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/Rothera","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/Syowa","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/Troll","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "AQ", "country_name" => "Antarctica", "time_zone" => "Antarctica/Vostok","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "AG", "country_name" => "Antigua and Barbuda", "time_zone" => "America/Antigua","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Buenos_Aires","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Catamarca","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Cordoba","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Jujuy","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/La_Rioja","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Mendoza","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Rio_Gallegos","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Salta","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/San_Juan","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/San_Luis","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Tucuman","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AR", "country_name" => "Argentina", "time_zone" => "America/Argentina/Ushuaia","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "AM", "country_name" => "Armenia", "time_zone" => "Asia/Yerevan","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "AW", "country_name" => "Aruba", "time_zone" => "America/Aruba","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Antarctica/Macquarie","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Adelaide","gmt_offset" => "UTC +09:30" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Brisbane","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Broken_Hill","gmt_offset" => "UTC +09:30" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Currie","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Darwin","gmt_offset" => "UTC +09:30" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Eucla","gmt_offset" => "UTC +08:45" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Hobart","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Lindeman","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Lord_Howe","gmt_offset" => "UTC +10:30" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Melbourne","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Perth","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "AU", "country_name" => "Australia", "time_zone" => "Australia/Sydney","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "AT", "country_name" => "Austria", "time_zone" => "Europe/Vienna","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "AZ", "country_name" => "Azerbaijan", "time_zone" => "Asia/Baku","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "BS", "country_name" => "Bahamas", "time_zone" => "America/Nassau","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BH", "country_name" => "Bahrain", "time_zone" => "Asia/Bahrain","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "BD", "country_name" => "Bangladesh", "time_zone" => "Asia/Dhaka","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "BB", "country_name" => "Barbados", "time_zone" => "America/Barbados","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BY", "country_name" => "Belarus", "time_zone" => "Europe/Minsk","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "BE", "country_name" => "Belgium", "time_zone" => "Europe/Brussels","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "BZ", "country_name" => "Belize", "time_zone" => "America/Belize","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "BJ", "country_name" => "Benin", "time_zone" => "Africa/Porto-Novo","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "BM", "country_name" => "Bermuda", "time_zone" => "Atlantic/Bermuda","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "BT", "country_name" => "Bhutan", "time_zone" => "Asia/Thimphu","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "BO", "country_name" => "Bolivia, Plurinational State of", "time_zone" => "America/La_Paz","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BQ", "country_name" => "Bonaire, Sint Eustatius and Saba", "time_zone" => "America/Kralendijk","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BA", "country_name" => "Bosnia and Herzegovina", "time_zone" => "Europe/Sarajevo","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "BW", "country_name" => "Botswana", "time_zone" => "Africa/Gaborone","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Araguaina","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Bahia","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Belem","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Boa_Vista","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Campo_Grande","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Cuiaba","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Eirunepe","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Fortaleza","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Maceio","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Manaus","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Noronha","gmt_offset" => "UTC -02:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Porto_Velho","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Recife","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Rio_Branco","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Santarem","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "BR", "country_name" => "Brazil", "time_zone" => "America/Sao_Paulo","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "IO", "country_name" => "British Indian Ocean Territory", "time_zone" => "Indian/Chagos","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "BN", "country_name" => "Brunei Darussalam", "time_zone" => "Asia/Brunei","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "BG", "country_name" => "Bulgaria", "time_zone" => "Europe/Sofia","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "BF", "country_name" => "Burkina Faso", "time_zone" => "Africa/Ouagadougou","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "BI", "country_name" => "Burundi", "time_zone" => "Africa/Bujumbura","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "KH", "country_name" => "Cambodia", "time_zone" => "Asia/Phnom_Penh","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "CM", "country_name" => "Cameroon", "time_zone" => "Africa/Douala","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Atikokan","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Blanc-Sablon","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Cambridge_Bay","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Creston","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Dawson","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Dawson_Creek","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Edmonton","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Fort_Nelson","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Glace_Bay","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Goose_Bay","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Halifax","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Inuvik","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Iqaluit","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Moncton","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Nipigon","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Pangnirtung","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Rainy_River","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Rankin_Inlet","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Regina","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Resolute","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/St_Johns","gmt_offset" => "UTC -02:30" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Swift_Current","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Thunder_Bay","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Toronto","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Vancouver","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Whitehorse","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Winnipeg","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "CA", "country_name" => "Canada", "time_zone" => "America/Yellowknife","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "CV", "country_name" => "Cape Verde", "time_zone" => "Atlantic/Cape_Verde","gmt_offset" => "UTC -01:00" ]);
Timezone::create([ "country_code" => "KY", "country_name" => "Cayman Islands", "time_zone" => "America/Cayman","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "CF", "country_name" => "Central African Republic", "time_zone" => "Africa/Bangui","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "TD", "country_name" => "Chad", "time_zone" => "Africa/Ndjamena","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "CL", "country_name" => "Chile", "time_zone" => "America/Punta_Arenas","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "CL", "country_name" => "Chile", "time_zone" => "America/Santiago","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CL", "country_name" => "Chile", "time_zone" => "Pacific/Easter","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "CN", "country_name" => "China", "time_zone" => "Asia/Shanghai","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "CN", "country_name" => "China", "time_zone" => "Asia/Urumqi","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "CX", "country_name" => "Christmas Island", "time_zone" => "Indian/Christmas","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "CC", "country_name" => "Cocos (Keeling) Islands", "time_zone" => "Indian/Cocos","gmt_offset" => "UTC +06:30" ]);
Timezone::create([ "country_code" => "CO", "country_name" => "Colombia", "time_zone" => "America/Bogota","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "KM", "country_name" => "Comoros", "time_zone" => "Indian/Comoro","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "CG", "country_name" => "Congo", "time_zone" => "Africa/Brazzaville","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "CD", "country_name" => "Congo, the Democratic Republic of the", "time_zone" => "Africa/Kinshasa","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "CD", "country_name" => "Congo, the Democratic Republic of the", "time_zone" => "Africa/Lubumbashi","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "CK", "country_name" => "Cook Islands", "time_zone" => "Pacific/Rarotonga","gmt_offset" => "UTC -10:00" ]);
Timezone::create([ "country_code" => "CR", "country_name" => "Costa Rica", "time_zone" => "America/Costa_Rica","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "HR", "country_name" => "Croatia", "time_zone" => "Europe/Zagreb","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "CU", "country_name" => "Cuba", "time_zone" => "America/Havana","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CW", "country_name" => "Curaçao", "time_zone" => "America/Curacao","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "CY", "country_name" => "Cyprus", "time_zone" => "Asia/Famagusta","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "CY", "country_name" => "Cyprus", "time_zone" => "Asia/Nicosia","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "CZ", "country_name" => "Czech Republic", "time_zone" => "Europe/Prague","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "CI", "country_name" => "Côte d'Ivoire", "time_zone" => "Africa/Abidjan","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "DK", "country_name" => "Denmark", "time_zone" => "Europe/Copenhagen","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "DJ", "country_name" => "Djibouti", "time_zone" => "Africa/Djibouti","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "DM", "country_name" => "Dominica", "time_zone" => "America/Dominica","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "DO", "country_name" => "Dominican Republic", "time_zone" => "America/Santo_Domingo","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "EC", "country_name" => "Ecuador", "time_zone" => "America/Guayaquil","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "EC", "country_name" => "Ecuador", "time_zone" => "Pacific/Galapagos","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "EG", "country_name" => "Egypt", "time_zone" => "Africa/Cairo","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "SV", "country_name" => "El Salvador", "time_zone" => "America/El_Salvador","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "GQ", "country_name" => "Equatorial Guinea", "time_zone" => "Africa/Malabo","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "ER", "country_name" => "Eritrea", "time_zone" => "Africa/Asmara","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "EE", "country_name" => "Estonia", "time_zone" => "Europe/Tallinn","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "ET", "country_name" => "Ethiopia", "time_zone" => "Africa/Addis_Ababa","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "FK", "country_name" => "Falkland Islands (Malvinas)", "time_zone" => "Atlantic/Stanley","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "FO", "country_name" => "Faroe Islands", "time_zone" => "Atlantic/Faroe","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "FJ", "country_name" => "Fiji", "time_zone" => "Pacific/Fiji","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "FI", "country_name" => "Finland", "time_zone" => "Europe/Helsinki","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "FR", "country_name" => "France", "time_zone" => "Europe/Paris","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "GF", "country_name" => "French Guiana", "time_zone" => "America/Cayenne","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "PF", "country_name" => "French Polynesia", "time_zone" => "Pacific/Gambier","gmt_offset" => "UTC -09:00" ]);
Timezone::create([ "country_code" => "PF", "country_name" => "French Polynesia", "time_zone" => "Pacific/Marquesas","gmt_offset" => "UTC -09:30" ]);
Timezone::create([ "country_code" => "PF", "country_name" => "French Polynesia", "time_zone" => "Pacific/Tahiti","gmt_offset" => "UTC -10:00" ]);
Timezone::create([ "country_code" => "TF", "country_name" => "French Southern Territories", "time_zone" => "Indian/Kerguelen","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "GA", "country_name" => "Gabon", "time_zone" => "Africa/Libreville","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "GM", "country_name" => "Gambia", "time_zone" => "Africa/Banjul","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "GE", "country_name" => "Georgia", "time_zone" => "Asia/Tbilisi","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "DE", "country_name" => "Germany", "time_zone" => "Europe/Berlin","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "DE", "country_name" => "Germany", "time_zone" => "Europe/Busingen","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "GH", "country_name" => "Ghana", "time_zone" => "Africa/Accra","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "GI", "country_name" => "Gibraltar", "time_zone" => "Europe/Gibraltar","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "GR", "country_name" => "Greece", "time_zone" => "Europe/Athens","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "GL", "country_name" => "Greenland", "time_zone" => "America/Danmarkshavn","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "GL", "country_name" => "Greenland", "time_zone" => "America/Nuuk","gmt_offset" => "UTC -02:00" ]);
Timezone::create([ "country_code" => "GL", "country_name" => "Greenland", "time_zone" => "America/Scoresbysund","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "GL", "country_name" => "Greenland", "time_zone" => "America/Thule","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "GD", "country_name" => "Grenada", "time_zone" => "America/Grenada","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "GP", "country_name" => "Guadeloupe", "time_zone" => "America/Guadeloupe","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "GU", "country_name" => "Guam", "time_zone" => "Pacific/Guam","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "GT", "country_name" => "Guatemala", "time_zone" => "America/Guatemala","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "GG", "country_name" => "Guernsey", "time_zone" => "Europe/Guernsey","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "GN", "country_name" => "Guinea", "time_zone" => "Africa/Conakry","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "GW", "country_name" => "Guinea-Bissau", "time_zone" => "Africa/Bissau","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "GY", "country_name" => "Guyana", "time_zone" => "America/Guyana","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "HT", "country_name" => "Haiti", "time_zone" => "America/Port-au-Prince","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "VA", "country_name" => "Holy See (Vatican City State)", "time_zone" => "Europe/Vatican","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "HN", "country_name" => "Honduras", "time_zone" => "America/Tegucigalpa","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "HK", "country_name" => "Hong Kong", "time_zone" => "Asia/Hong_Kong","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "HU", "country_name" => "Hungary", "time_zone" => "Europe/Budapest","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "IS", "country_name" => "Iceland", "time_zone" => "Atlantic/Reykjavik","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "IN", "country_name" => "India", "time_zone" => "Asia/Kolkata","gmt_offset" => "UTC +05:30" ]);
Timezone::create([ "country_code" => "ID", "country_name" => "Indonesia", "time_zone" => "Asia/Jakarta","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "ID", "country_name" => "Indonesia", "time_zone" => "Asia/Jayapura","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "ID", "country_name" => "Indonesia", "time_zone" => "Asia/Makassar","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "ID", "country_name" => "Indonesia", "time_zone" => "Asia/Pontianak","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "IR", "country_name" => "Iran, Islamic Republic of", "time_zone" => "Asia/Tehran","gmt_offset" => "UTC +04:30" ]);
Timezone::create([ "country_code" => "IQ", "country_name" => "Iraq", "time_zone" => "Asia/Baghdad","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "IE", "country_name" => "Ireland", "time_zone" => "Europe/Dublin","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "IM", "country_name" => "Isle of Man", "time_zone" => "Europe/Isle_of_Man","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "IL", "country_name" => "Israel", "time_zone" => "Asia/Jerusalem","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "IT", "country_name" => "Italy", "time_zone" => "Europe/Rome","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "JM", "country_name" => "Jamaica", "time_zone" => "America/Jamaica","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "JP", "country_name" => "Japan", "time_zone" => "Asia/Tokyo","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "JE", "country_name" => "Jersey", "time_zone" => "Europe/Jersey","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "JO", "country_name" => "Jordan", "time_zone" => "Asia/Amman","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "KZ", "country_name" => "Kazakhstan", "time_zone" => "Asia/Almaty","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "KZ", "country_name" => "Kazakhstan", "time_zone" => "Asia/Aqtau","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "KZ", "country_name" => "Kazakhstan", "time_zone" => "Asia/Aqtobe","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "KZ", "country_name" => "Kazakhstan", "time_zone" => "Asia/Atyrau","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "KZ", "country_name" => "Kazakhstan", "time_zone" => "Asia/Oral","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "KZ", "country_name" => "Kazakhstan", "time_zone" => "Asia/Qostanay","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "KZ", "country_name" => "Kazakhstan", "time_zone" => "Asia/Qyzylorda","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "KE", "country_name" => "Kenya", "time_zone" => "Africa/Nairobi","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "KI", "country_name" => "Kiribati", "time_zone" => "Pacific/Enderbury","gmt_offset" => "UTC +13:00" ]);
Timezone::create([ "country_code" => "KI", "country_name" => "Kiribati", "time_zone" => "Pacific/Kiritimati","gmt_offset" => "UTC +14:00" ]);
Timezone::create([ "country_code" => "KI", "country_name" => "Kiribati", "time_zone" => "Pacific/Tarawa","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "KP", "country_name" => "Korea Democratic People Republic of", "time_zone" => "Asia/Pyongyang","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "KR", "country_name" => "Korea Republic of", "time_zone" => "Asia/Seoul","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "KW", "country_name" => "Kuwait", "time_zone" => "Asia/Kuwait","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "KG", "country_name" => "Kyrgyzstan", "time_zone" => "Asia/Bishkek","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "LA", "country_name" => "Lao People'/s Democratic Republic", "time_zone" => "Asia/Vientiane","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "LV", "country_name" => "Latvia", "time_zone" => "Europe/Riga","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "LB", "country_name" => "Lebanon", "time_zone" => "Asia/Beirut","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "LS", "country_name" => "Lesotho", "time_zone" => "Africa/Maseru","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "LR", "country_name" => "Liberia", "time_zone" => "Africa/Monrovia","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "LY", "country_name" => "Libya", "time_zone" => "Africa/Tripoli","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "LI", "country_name" => "Liechtenstein", "time_zone" => "Europe/Vaduz","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "LT", "country_name" => "Lithuania", "time_zone" => "Europe/Vilnius","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "LU", "country_name" => "Luxembourg", "time_zone" => "Europe/Luxembourg","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "MO", "country_name" => "Macao", "time_zone" => "Asia/Macau","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "MK", "country_name" => "Macedonia, the Former Yugoslav Republic of", "time_zone" => "Europe/Skopje","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "MG", "country_name" => "Madagascar", "time_zone" => "Indian/Antananarivo","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "MW", "country_name" => "Malawi", "time_zone" => "Africa/Blantyre","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "MY", "country_name" => "Malaysia", "time_zone" => "Asia/Kuala_Lumpur","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "MY", "country_name" => "Malaysia", "time_zone" => "Asia/Kuching","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "MV", "country_name" => "Maldives", "time_zone" => "Indian/Maldives","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "ML", "country_name" => "Mali", "time_zone" => "Africa/Bamako","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "MT", "country_name" => "Malta", "time_zone" => "Europe/Malta","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "MH", "country_name" => "Marshall Islands", "time_zone" => "Pacific/Kwajalein","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "MH", "country_name" => "Marshall Islands", "time_zone" => "Pacific/Majuro","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "MQ", "country_name" => "Martinique", "time_zone" => "America/Martinique","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "MR", "country_name" => "Mauritania", "time_zone" => "Africa/Nouakchott","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "MU", "country_name" => "Mauritius", "time_zone" => "Indian/Mauritius","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "YT", "country_name" => "Mayotte", "time_zone" => "Indian/Mayotte","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Bahia_Banderas","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Cancun","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Chihuahua","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Hermosillo","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Matamoros","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Mazatlan","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Merida","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Mexico_City","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Monterrey","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Ojinaga","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "MX", "country_name" => "Mexico", "time_zone" => "America/Tijuana","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "FM", "country_name" => "Micronesia, Federated States of", "time_zone" => "Pacific/Chuuk","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "FM", "country_name" => "Micronesia, Federated States of", "time_zone" => "Pacific/Kosrae","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "FM", "country_name" => "Micronesia, Federated States of", "time_zone" => "Pacific/Pohnpei","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "MD", "country_name" => "Moldova, Republic of", "time_zone" => "Europe/Chisinau","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "MC", "country_name" => "Monaco", "time_zone" => "Europe/Monaco","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "MN", "country_name" => "Mongolia", "time_zone" => "Asia/Choibalsan","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "MN", "country_name" => "Mongolia", "time_zone" => "Asia/Hovd","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "MN", "country_name" => "Mongolia", "time_zone" => "Asia/Ulaanbaatar","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "ME", "country_name" => "Montenegro", "time_zone" => "Europe/Podgorica","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "MS", "country_name" => "Montserrat", "time_zone" => "America/Montserrat","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "MA", "country_name" => "Morocco", "time_zone" => "Africa/Casablanca","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "MZ", "country_name" => "Mozambique", "time_zone" => "Africa/Maputo","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "MM", "country_name" => "Myanmar", "time_zone" => "Asia/Yangon","gmt_offset" => "UTC +06:30" ]);
Timezone::create([ "country_code" => "NA", "country_name" => "Namibia", "time_zone" => "Africa/Windhoek","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "NR", "country_name" => "Nauru", "time_zone" => "Pacific/Nauru","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "NP", "country_name" => "Nepal", "time_zone" => "Asia/Kathmandu","gmt_offset" => "UTC +05:45" ]);
Timezone::create([ "country_code" => "NL", "country_name" => "Netherlands", "time_zone" => "Europe/Amsterdam","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "NC", "country_name" => "New Caledonia", "time_zone" => "Pacific/Noumea","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "NZ", "country_name" => "New Zealand", "time_zone" => "Pacific/Auckland","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "NZ", "country_name" => "New Zealand", "time_zone" => "Pacific/Chatham","gmt_offset" => "UTC +12:45" ]);
Timezone::create([ "country_code" => "NI", "country_name" => "Nicaragua", "time_zone" => "America/Managua","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "NE", "country_name" => "Niger", "time_zone" => "Africa/Niamey","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "NG", "country_name" => "Nigeria", "time_zone" => "Africa/Lagos","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "NU", "country_name" => "Niue", "time_zone" => "Pacific/Niue","gmt_offset" => "UTC -11:00" ]);
Timezone::create([ "country_code" => "NF", "country_name" => "Norfolk Island", "time_zone" => "Pacific/Norfolk","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "MP", "country_name" => "Northern Mariana Islands", "time_zone" => "Pacific/Saipan","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "NO", "country_name" => "Norway", "time_zone" => "Europe/Oslo","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "OM", "country_name" => "Oman", "time_zone" => "Asia/Muscat","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "PK", "country_name" => "Pakistan", "time_zone" => "Asia/Karachi","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "PW", "country_name" => "Palau", "time_zone" => "Pacific/Palau","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "PS", "country_name" => "Palestine, State of", "time_zone" => "Asia/Gaza","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "PS", "country_name" => "Palestine, State of", "time_zone" => "Asia/Hebron","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "PA", "country_name" => "Panama", "time_zone" => "America/Panama","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "PG", "country_name" => "Papua New Guinea", "time_zone" => "Pacific/Bougainville","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "PG", "country_name" => "Papua New Guinea", "time_zone" => "Pacific/Port_Moresby","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "PY", "country_name" => "Paraguay", "time_zone" => "America/Asuncion","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "PE", "country_name" => "Peru", "time_zone" => "America/Lima","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "PH", "country_name" => "Philippines", "time_zone" => "Asia/Manila","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "PN", "country_name" => "Pitcairn", "time_zone" => "Pacific/Pitcairn","gmt_offset" => "UTC -08:00" ]);
Timezone::create([ "country_code" => "PL", "country_name" => "Poland", "time_zone" => "Europe/Warsaw","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "PT", "country_name" => "Portugal", "time_zone" => "Atlantic/Azores","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "PT", "country_name" => "Portugal", "time_zone" => "Atlantic/Madeira","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "PT", "country_name" => "Portugal", "time_zone" => "Europe/Lisbon","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "PR", "country_name" => "Puerto Rico", "time_zone" => "America/Puerto_Rico","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "QA", "country_name" => "Qatar", "time_zone" => "Asia/Qatar","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "RO", "country_name" => "Romania", "time_zone" => "Europe/Bucharest","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Anadyr","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Barnaul","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Chita","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Irkutsk","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Kamchatka","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Khandyga","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Krasnoyarsk","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Magadan","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Novokuznetsk","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Novosibirsk","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Omsk","gmt_offset" => "UTC +06:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Sakhalin","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Srednekolymsk","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Tomsk","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Ust-Nera","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Vladivostok","gmt_offset" => "UTC +10:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Yakutsk","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Asia/Yekaterinburg","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Europe/Astrakhan","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Europe/Kaliningrad","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Europe/Kirov","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Europe/Moscow","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Europe/Samara","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Europe/Saratov","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Europe/Ulyanovsk","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "RU", "country_name" => "Russian Federation", "time_zone" => "Europe/Volgograd","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "RW", "country_name" => "Rwanda", "time_zone" => "Africa/Kigali","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "RE", "country_name" => "Réunion", "time_zone" => "Indian/Reunion","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "BL", "country_name" => "Saint Barthélemy", "time_zone" => "America/St_Barthelemy","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "SH", "country_name" => "Saint Helena, Ascension and Tristan da Cunha", "time_zone" => "Atlantic/St_Helena","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "KN", "country_name" => "Saint Kitts and Nevis", "time_zone" => "America/St_Kitts","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "LC", "country_name" => "Saint Lucia", "time_zone" => "America/St_Lucia","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "MF", "country_name" => "Saint Martin (French part)", "time_zone" => "America/Marigot","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "PM", "country_name" => "Saint Pierre and Miquelon", "time_zone" => "America/Miquelon","gmt_offset" => "UTC -02:00" ]);
Timezone::create([ "country_code" => "VC", "country_name" => "Saint Vincent and the Grenadines", "time_zone" => "America/St_Vincent","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "WS", "country_name" => "Samoa", "time_zone" => "Pacific/Apia","gmt_offset" => "UTC +13:00" ]);
Timezone::create([ "country_code" => "SM", "country_name" => "San Marino", "time_zone" => "Europe/San_Marino","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "ST", "country_name" => "Sao Tome and Principe", "time_zone" => "Africa/Sao_Tome","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "SA", "country_name" => "Saudi Arabia", "time_zone" => "Asia/Riyadh","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "SN", "country_name" => "Senegal", "time_zone" => "Africa/Dakar","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "RS", "country_name" => "Serbia", "time_zone" => "Europe/Belgrade","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "SC", "country_name" => "Seychelles", "time_zone" => "Indian/Mahe","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "SL", "country_name" => "Sierra Leone", "time_zone" => "Africa/Freetown","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "SG", "country_name" => "Singapore", "time_zone" => "Asia/Singapore","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "SX", "country_name" => "Sint Maarten (Dutch part)", "time_zone" => "America/Lower_Princes","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "SK", "country_name" => "Slovakia", "time_zone" => "Europe/Bratislava","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "SI", "country_name" => "Slovenia", "time_zone" => "Europe/Ljubljana","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "SB", "country_name" => "Solomon Islands", "time_zone" => "Pacific/Guadalcanal","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "SO", "country_name" => "Somalia", "time_zone" => "Africa/Mogadishu","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "ZA", "country_name" => "South Africa", "time_zone" => "Africa/Johannesburg","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "GS", "country_name" => "South Georgia and the South Sandwich Islands", "time_zone" => "Atlantic/South_Georgia","gmt_offset" => "UTC -02:00" ]);
Timezone::create([ "country_code" => "SS", "country_name" => "South Sudan", "time_zone" => "Africa/Juba","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "ES", "country_name" => "Spain", "time_zone" => "Africa/Ceuta","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "ES", "country_name" => "Spain", "time_zone" => "Atlantic/Canary","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "ES", "country_name" => "Spain", "time_zone" => "Europe/Madrid","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "LK", "country_name" => "Sri Lanka", "time_zone" => "Asia/Colombo","gmt_offset" => "UTC +05:30" ]);
Timezone::create([ "country_code" => "SD", "country_name" => "Sudan", "time_zone" => "Africa/Khartoum","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "SR", "country_name" => "Suriname", "time_zone" => "America/Paramaribo","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "SJ", "country_name" => "Svalbard and Jan Mayen", "time_zone" => "Arctic/Longyearbyen","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "SZ", "country_name" => "Swaziland", "time_zone" => "Africa/Mbabane","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "SE", "country_name" => "Sweden", "time_zone" => "Europe/Stockholm","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "CH", "country_name" => "Switzerland", "time_zone" => "Europe/Zurich","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "SY", "country_name" => "Syrian Arab Republic", "time_zone" => "Asia/Damascus","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "TW", "country_name" => "Taiwan, Province of China", "time_zone" => "Asia/Taipei","gmt_offset" => "UTC +08:00" ]);
Timezone::create([ "country_code" => "TJ", "country_name" => "Tajikistan", "time_zone" => "Asia/Dushanbe","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "TZ", "country_name" => "Tanzania, United Republic of", "time_zone" => "Africa/Dar_es_Salaam","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "TH", "country_name" => "Thailand", "time_zone" => "Asia/Bangkok","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "TL", "country_name" => "Timor-Leste", "time_zone" => "Asia/Dili","gmt_offset" => "UTC +09:00" ]);
Timezone::create([ "country_code" => "TG", "country_name" => "Togo", "time_zone" => "Africa/Lome","gmt_offset" => "UTC" ]);
Timezone::create([ "country_code" => "TK", "country_name" => "Tokelau", "time_zone" => "Pacific/Fakaofo","gmt_offset" => "UTC +13:00" ]);
Timezone::create([ "country_code" => "TO", "country_name" => "Tonga", "time_zone" => "Pacific/Tongatapu","gmt_offset" => "UTC +13:00" ]);
Timezone::create([ "country_code" => "TT", "country_name" => "Trinidad and Tobago", "time_zone" => "America/Port_of_Spain","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "TN", "country_name" => "	Tunisia", "time_zone" => "Africa/Tunis","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "TR", "country_name" => "Turkey", "time_zone" => "Europe/Istanbul","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "TM", "country_name" => "Turkmenistan", "time_zone" => "Asia/Ashgabat","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "TC", "country_name" => "Turks and Caicos Islands", "time_zone" => "America/Grand_Turk","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "TV", "country_name" => "Tuvalu", "time_zone" => "Pacific/Funafuti","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "UG", "country_name" => "Uganda", "time_zone" => "Africa/Kampala","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "UA", "country_name" => "Ukraine", "time_zone" => "Europe/Kiev","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "UA", "country_name" => "Ukraine", "time_zone" => "Europe/Simferopol","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "UA", "country_name" => "Ukraine", "time_zone" => "Europe/Uzhgorod","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "UA", "country_name" => "Ukraine", "time_zone" => "Europe/Zaporozhye","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "AE", "country_name" => "United Arab Emirates	Asia/Dubai","gmt_offset" => "UTC +04:00" ]);
Timezone::create([ "country_code" => "GB", "country_name" => "United Kingdom", "time_zone" => "Europe/London","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Adak","gmt_offset" => "UTC -09:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Anchorage","gmt_offset" => "UTC -08:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Boise","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Chicago","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Denver","gmt_offset" => "UTC -06:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Detroit","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Indiana/Indianapolis","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Indiana/Knox","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Indiana/Marengo","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Indiana/Petersburg","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Indiana/Tell_City","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Indiana/Vevay","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Indiana/Vincennes","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Indiana/Winamac","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Juneau","gmt_offset" => "UTC -08:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Kentucky/Louisville","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Kentucky/Monticello","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Los_Angeles","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Menominee","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Metlakatla","gmt_offset" => "UTC -08:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/New_York","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Nome","gmt_offset" => "UTC -08:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/North_Dakota/Beulah","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/North_Dakota/Center","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/North_Dakota/New_Salem","gmt_offset" => "UTC -05:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Phoenix","gmt_offset" => "UTC -07:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Sitka","gmt_offset" => "UTC -08:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "America/Yakutat","gmt_offset" => "UTC -08:00" ]);
Timezone::create([ "country_code" => "US", "country_name" => "United States", "time_zone" => "Pacific/Honolulu","gmt_offset" => "UTC -10:00" ]);
Timezone::create([ "country_code" => "UM", "country_name" => "United States Minor Outlying Islands", "time_zone" => "Pacific/Midway","gmt_offset" => "UTC -11:00" ]);
Timezone::create([ "country_code" => "UM", "country_name" => "United States Minor Outlying Islands", "time_zone" => "Pacific/Wake","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "UY", "country_name" => "Uruguay", "time_zone" => "America/Montevideo","gmt_offset" => "UTC -03:00" ]);
Timezone::create([ "country_code" => "UZ", "country_name" => "Uzbekistan", "time_zone" => "Asia/Samarkand","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "UZ", "country_name" => "Uzbekistan", "time_zone" => "Asia/Tashkent","gmt_offset" => "UTC +05:00" ]);
Timezone::create([ "country_code" => "VU", "country_name" => "Vanuatu", "time_zone" => "Pacific/Efate","gmt_offset" => "UTC +11:00" ]);
Timezone::create([ "country_code" => "VE", "country_name" => "Venezuela, Bolivarian Republic of", "time_zone" => "America/Caracas","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "VN", "country_name" => "Viet Nam", "time_zone" => "Asia/Ho_Chi_Minh","gmt_offset" => "UTC +07:00" ]);
Timezone::create([ "country_code" => "VG", "country_name" => "Virgin Islands, British", "time_zone" => "America/Tortola","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "VI", "country_name" => "Virgin Islands, U.S.", "time_zone" => "America/St_Thomas","gmt_offset" => "UTC -04:00" ]);
Timezone::create([ "country_code" => "WF", "country_name" => "Wallis and Futuna", "time_zone" => "Pacific/Wallis","gmt_offset" => "UTC +12:00" ]);
Timezone::create([ "country_code" => "EH", "country_name" => "Western Sahara", "time_zone" => "Africa/El_Aaiun","gmt_offset" => "UTC +01:00" ]);
Timezone::create([ "country_code" => "YE", "country_name" => "Yemen", "time_zone" => "Asia/Aden","gmt_offset" => "UTC +03:00" ]);
Timezone::create([ "country_code" => "ZM", "country_name" => "Zambia", "time_zone" => "Africa/Lusaka","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "ZW", "country_name" => "Zimbabwe", "time_zone" => "Africa/Harare","gmt_offset" => "UTC +02:00" ]);
Timezone::create([ "country_code" => "AX", "country_name" => "Åland Islands", "time_zone" => "Europe/Mariehamn","gmt_offset" => "UTC +03:00" ]);

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('timezones');
    }
}
